server:
  port: 8080

spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      generate-ddl: false
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate: INFO
    org.apache.ibatis: DEBUG
    org.apache.shardingsphere: DEBUG
    com.mysql: DEBUG
