server:
  port: 8080

spring:
  profiles:
    active: @spring.config.activate.on-profile@
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: false

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      # http://localhost:8080/h2-console/.
      enabled: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/jpatestdb?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: test
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatestdb
    driverClassName: org.postgresql.Driver
    username: test
    password: test
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
