server:
  port: 8080

spring:
  profiles:
    active: @spring.config.activate.on-profile@
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: false