server:
  port: 8080

spring:
  datasource:
    username: nc_resource_user
    password: PbF1_02QqF
    url: "jdbc:mysql://10.1.207.183:3810/nc_resource?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true"

logging:
  level:
    com:
      coolbeevip:
        ignite:
          mybatis:
            repository: DEBUG