name: tutorials-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MAVEN_OPTS: -Xmx4g -Xms1g -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3

jobs:
  build:
    timeout-minutes: 180
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/
            !~/.m2/repository/org/coolbeevip
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Show the first log message
        run: git log -n1

      - name: Build with Maven
        if: ${{ success() }}
        run: ./mvnw -T 1.5C -B package verify --file pom.xml
